---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == "Debian"

- name: Install required packages (Debian)
  ansible.builtin.apt:
    name:
      - zsh
      - git
      - curl
      - wget
      - unzip
      - fontconfig
      - build-essential
      - lsd
      - bat
      - fzf
      - ripgrep
      - htop
      - neofetch
      - python3
      - python3-pip
      - jq
      - net-tools
      - iproute2
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install Homebrew packages (macOS)
  community.general.homebrew:
    name:
      - zsh
      - git
      - curl
      - wget
      - unzip
      - lsd
      - bat
      - fzf
      - ripgrep
      - htop
      - neofetch
      - python3
      - jq
    state: present
  become: false
  when: ansible_facts['os_family'] == "Darwin"